#!/usr/bin/env python3
"""Give every Amazon "check price" button the same wording, and a screen-reader label naming the product.

    python3 scripts/standardize_ctas.py          # rewrite the buttons
    python3 scripts/standardize_ctas.py --check  # verify only, exit 1 if any button is off-standard

Buttons are the <a class="btn-check-price"> links that point at amazon.com or amazon.ca:
    amazon.com  ->  Check Price on Amazon →
    amazon.ca   ->  Check Price on Amazon.ca →
The button says where it goes (never disguised) and carries aria-label="Check Price on Amazon: <product>"
so a list of identical buttons is still understandable to a screen reader. The product name is the nearest
<h3> (or the section's <h2>) above the button. Inline text links (retailer names, product-name links) are
left alone. Gift guides are generated by build_gift_guides.py, which writes the same wording.
"""
import glob
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BTN_RE = re.compile(r'<a ((?:(?!>).)*?href="https?://(?:www\.)?amazon\.(com|ca)[^"]*"(?:(?!>).)*?)>(.*?)</a>', re.S)
problems = []


def read(p):
    with open(p, encoding="utf-8", newline="") as f:
        return f.read()


def write(p, t):
    with open(p, "w", encoding="utf-8", newline="") as f:
        f.write(t)


def text(s):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", s))).strip()


def product_name(page, pos):
    """Nearest h3 after the last h2 before pos; else that h2's text (minus the '1.' numbering and any ': tagline')."""
    h2s = list(re.finditer(r"<h2[^>]*>(.*?)</h2>", page[:pos], re.S))
    start = h2s[-1].end() if h2s else 0
    h3s = list(re.finditer(r"<h3[^>]*>(.*?)</h3>", page[start:pos], re.S))
    raw = h3s[-1].group(1) if h3s else (h2s[-1].group(1) if h2s else "")
    name = text(raw)
    name = re.sub(r"^\d+\.\s*", "", name)
    name = re.split(r":| – | - ", name)[0].strip()
    return name


def fix(path, check):
    old = read(path)
    if "btn-check-price" not in old:
        return
    rel = path.relative_to(ROOT).as_posix()

    def sub(m):
        attrs, dom, inner = m.group(1), m.group(2), m.group(3)
        if 'class="btn-check-price"' not in attrs:
            return m.group(0)
        if 'data-cta="' in attrs and 'data-cta="product_section"' not in attrs:
            return m.group(0)  # buttons placed by other scripts (e.g. after a table) carry their own label
        label = "Check Price on Amazon.ca →" if dom == "ca" else "Check Price on Amazon →"
        attrs = re.sub(r'\s*(?:aria-label|data-cta|data-product)="[^"]*"', "", attrs)
        name = product_name(old, m.start())
        if name:
            attrs += f' data-cta="product_section" data-product="{html.escape(name, quote=True)}"'
            attrs += f' aria-label="Check Price on Amazon{".ca" if dom == "ca" else ""}: {html.escape(name, quote=True)}"'
        return f"<a {attrs}>{label}</a>"

    new = BTN_RE.sub(sub, old)
    if new != old:
        if check:
            problems.append(f"{rel}: Amazon button wording or aria-label is off-standard (run standardize_ctas.py)")
        else:
            write(path, new)


def main():
    check = "--check" in sys.argv
    files = [Path(p) for pat in ("blog/*.html", "guides/*.html", "gift-guides/*.html") for p in glob.glob(str(ROOT / pat))]
    for f in sorted(files):
        fix(f, check)
    if problems:
        print("\n".join(f"x {p}" for p in problems))
        sys.exit(1)
    print("amazon buttons OK" if check else "amazon buttons standardised")


if __name__ == "__main__":
    main()
